
# Run with Python 2
# Functionality to convert the output of an implementation file which is output from LIGHTER (in C-like syntax) to a TFC [http://webhome.cs.uvic.ca/~dmaslov/mach-read.html] file

file_name = 'test.c'
impl_file = open(file_name, 'r')
tfc_file = open(file_name.split('.')[0]+'.tfc', 'w')

import sys
opening_msg = 'This file is auto-generated by '+sys.argv[0]

print >> tfc_file, '# '+opening_msg

# copy the content
for f in impl_file.readlines():
	f = f.strip()
	print >> tfc_file, '# '+f

impl_file.seek(0)
for f in impl_file.readlines():
	f = f.strip()
	# ignore comments
	if f.startswith('//'):
		pass
	elif 

impl_file.close()
tfc_file.close()	
